AWSTemplateFormatVersion: 2010-09-09
Description: >
  AWS Data Wrangler
  Test Arena

Parameters:
  VpcId:
    Type: String
    Description: Redshift VPC ID
  SubnetId:
    Type: String
    Description: Redshift Subnet ID
  SubnetId2:
    Type: String
    Description: Redshift Subnet ID
  SubnetAz:
    Type: String
    Description: Subnet AZ
  Password:
    Type: String
    Description: Redshift Password
  TestUser:
    Type: String
    Description: AWS User that will running the tests on the CLI

Resources:

  KmsKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/aws-data-wrangler-test-key
      TargetKeyId:
        Ref: KmsKey

  KmsKey:
    Type: AWS::KMS::Key
    Properties:
      Description: "Aws Data Wrangler Test Key."
      KeyPolicy:
        Version: "2012-10-17"
        Id: "aws-data-wrangler-test-key"
        Statement:
          - Sid: "Enable IAM User Permissions"
            Effect: "Allow"
            Principal:
              AWS: !Join ["", ["arn:aws:iam::", !Ref "AWS::AccountId", ":root"]]
            Action: "kms:*"
            Resource: "*"
          - Sid: "Allow administration of the key"
            Effect: "Allow"
            Principal:
              AWS: !Join ["", ["arn:aws:iam::", !Ref "AWS::AccountId", ":user/", !Ref TestUser]]
            Action:
              - "kms:Create*"
              - "kms:Describe*"
              - "kms:Enable*"
              - "kms:List*"
              - "kms:Put*"
              - "kms:Update*"
              - "kms:Revoke*"
              - "kms:Disable*"
              - "kms:Get*"
              - "kms:Delete*"
              - "kms:ScheduleKeyDeletion"
              - "kms:CancelKeyDeletion"

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: CleaningUp
            Status: Enabled
            ExpirationInDays: 1
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1
            NoncurrentVersionExpirationInDays: 1

  RedshiftRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - redshift.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: S3GetAndList
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "s3:Get*"
                  - "s3:List*"
                  - "s3:Put*"
                Resource:
                  - !Join ['', ['arn:aws:s3:::', !Ref Bucket]]
                  - !Join ['', ['arn:aws:s3:::', !Ref Bucket, /*]]

  RedshiftSubnetGroup:
    Type: AWS::Redshift::ClusterSubnetGroup
    Properties:
      Description: AWS Data Wrangler Test Arena - Redshift Subnet Group
      SubnetIds:
        - Ref: SubnetId

  DatabaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: AWS Data Wrangler Test Arena - Redshift security group

  DatabaseSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: "Self Referencing"
      GroupId: !Ref DatabaseSecurityGroup
      IpProtocol: "-1"
      FromPort: 0
      ToPort: 65535
      SourceSecurityGroupId: !Ref DatabaseSecurityGroup

  Redshift:
    Type: AWS::Redshift::Cluster
    DependsOn:
      - DatabaseSecurityGroup
      - RedshiftSubnetGroup
      - RedshiftRole
    Properties:
      DBName: test
      MasterUsername: test
      MasterUserPassword: !Ref Password
      NodeType: dc2.large
      ClusterType: single-node
      VpcSecurityGroupIds:
        - !Ref DatabaseSecurityGroup
      ClusterSubnetGroupName: !Ref RedshiftSubnetGroup
      PubliclyAccessible: true
      Port: 5439
      IamRoles:
        - !GetAtt RedshiftRole.Arn

  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: awswrangler_test
        Description: AWS Data Wrangler Test Arena - Glue Database

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 1

  LogStream:
    Type: AWS::Logs::LogStream
    Properties:
      LogGroupName: !Ref LogGroup

  RdsSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: RDS Database Subnet Group
      SubnetIds:
        - Ref: SubnetId
        - Ref: SubnetId2

  AuroraRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - rds.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: S3GetAndList
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "s3:Get*"
                  - "s3:List*"
                  - "s3:Put*"
                Resource:
                  - !Join ['', ['arn:aws:s3:::', !Ref Bucket]]
                  - !Join ['', ['arn:aws:s3:::', !Ref Bucket, /*]]

  PostgresParameterGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Description: Postgres 10
      Family: aurora-postgresql10
      Parameters:
        apg_plan_mgmt.capture_plan_baselines: "off"

  AuroraClusterPostgres:
    Type: AWS::RDS::DBCluster
    DependsOn:
      - PostgresParameterGroup
      - AuroraRole
      - RdsSubnetGroup
      - DatabaseSecurityGroup
    Properties:
      Engine: aurora-postgresql
      DBClusterIdentifier : postgres-cluster-wrangler
      MasterUsername: test
      MasterUserPassword: !Ref Password
      BackupRetentionPeriod: 1
      DBSubnetGroupName: !Ref RdsSubnetGroup
      VpcSecurityGroupIds:
        - !Ref DatabaseSecurityGroup
      DBClusterParameterGroupName: !Ref PostgresParameterGroup
      AssociatedRoles:
        - FeatureName: s3Import
          RoleArn: !GetAtt AuroraRole.Arn

  AuroraInstancePostgres:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: aurora-postgresql
      DBInstanceIdentifier: postgres-instance-wrangler
      DBClusterIdentifier: !Ref AuroraClusterPostgres
      DBInstanceClass: db.t3.medium
      DBSubnetGroupName: !Ref RdsSubnetGroup
      PubliclyAccessible: true

  MysqlParameterGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Description: Mysql 5.7
      Family: aurora-mysql5.7
      Parameters:
        aurora_load_from_s3_role: !GetAtt AuroraRole.Arn
        aws_default_s3_role: !GetAtt AuroraRole.Arn
        aurora_select_into_s3_role: !GetAtt AuroraRole.Arn

  AuroraClusterMysql:
    Type: AWS::RDS::DBCluster
    DependsOn:
      - MysqlParameterGroup
      - AuroraRole
      - RdsSubnetGroup
      - DatabaseSecurityGroup
    Properties:
      Engine: aurora-mysql
      DBClusterIdentifier: mysql-cluster-wrangler
      MasterUsername: test
      MasterUserPassword: !Ref Password
      BackupRetentionPeriod: 1
      DBSubnetGroupName: !Ref RdsSubnetGroup
      VpcSecurityGroupIds:
        - !Ref DatabaseSecurityGroup
      DBClusterParameterGroupName: !Ref MysqlParameterGroup
      AssociatedRoles:
        - RoleArn: !GetAtt AuroraRole.Arn

  AuroraInstanceMysql:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: aurora-mysql
      DBInstanceIdentifier: mysql-instance-wrangler
      DBClusterIdentifier: !Ref AuroraClusterMysql
      DBInstanceClass: db.t3.medium
      DBSubnetGroupName: !Ref RdsSubnetGroup
      PubliclyAccessible: true

  RedshiftGlueConnection:
    Type: AWS::Glue::Connection
    Properties:
      CatalogId: !Ref AWS::AccountId
      ConnectionInput:
        Description: Connect to Redshift.
        ConnectionType: "JDBC"
        PhysicalConnectionRequirements:
          AvailabilityZone: !Ref SubnetAz
          SecurityGroupIdList:
            - !Ref DatabaseSecurityGroup
          SubnetId: !Ref SubnetId
        ConnectionProperties:
          {
            "JDBC_CONNECTION_URL":
              !Join [
                "",
                [
                  "jdbc:redshift://",
                  !GetAtt Redshift.Endpoint.Address,
                  ":",
                  !GetAtt Redshift.Endpoint.Port,
                  "/",
                  test,
                ],
              ],
            "USERNAME": test,
            "PASSWORD": !Ref Password,
          }
        Name: "aws-data-wrangler-redshift"

  PostgresGlueConnection:
    Type: AWS::Glue::Connection
    Properties:
      CatalogId: !Ref AWS::AccountId
      ConnectionInput:
        Description: Connect to Aurora (PostgreSQL).
        ConnectionType: "JDBC"
        PhysicalConnectionRequirements:
          AvailabilityZone: !Ref SubnetAz
          SecurityGroupIdList:
            - !Ref DatabaseSecurityGroup
          SubnetId: !Ref SubnetId
        ConnectionProperties:
          {
            "JDBC_CONNECTION_URL":
              !Join [
                "",
                [
                  "jdbc:postgresql://",
                  !GetAtt AuroraInstancePostgres.Endpoint.Address,
                  ":",
                  !GetAtt AuroraInstancePostgres.Endpoint.Port,
                  "/",
                  postgres,
                ],
              ],
            "USERNAME": test,
            "PASSWORD": !Ref Password,
          }
        Name: "aws-data-wrangler-postgres"

  MysqlGlueConnection:
    Type: AWS::Glue::Connection
    Properties:
      CatalogId: !Ref AWS::AccountId
      ConnectionInput:
        Description: Connect to Aurora (MySQL).
        ConnectionType: "JDBC"
        PhysicalConnectionRequirements:
          AvailabilityZone: !Ref SubnetAz
          SecurityGroupIdList:
            - !Ref DatabaseSecurityGroup
          SubnetId: !Ref SubnetId
        ConnectionProperties:
          {
            "JDBC_CONNECTION_URL":
              !Join [
                "",
                [
                  "jdbc:mysql://",
                  !GetAtt AuroraInstanceMysql.Endpoint.Address,
                  ":",
                  !GetAtt AuroraInstanceMysql.Endpoint.Port,
                  "/",
                  test,
                ],
              ],
            "USERNAME": test,
            "PASSWORD": !Ref Password,
          }
        Name: "aws-data-wrangler-mysql"

Outputs:
  BucketName:
    Value: !Ref Bucket
    Description: Name of the S3 Bucket used for tests.
  RedshiftAddress:
    Value: !GetAtt Redshift.Endpoint.Address
    Description: Redshift Password.
  RedshiftPort:
    Value: !GetAtt Redshift.Endpoint.Port
    Description: Redshift Endpoint Port.
  Password:
    Value: !Ref Password
    Description: Password.
  RedshiftRole:
    Value: !GetAtt RedshiftRole.Arn
    Description: Redshift IAM role.
  GlueDatabaseName:
    Value: !Ref GlueDatabase
    Description: Glue Database Name.
  KmsKeyArn:
    Value: !GetAtt KmsKey.Arn
    Description: KMS Key ARN.
  LogGroupName:
    Value: !Ref LogGroup
    Description: LogGroup name.
  LogStream:
    Value: !Ref LogStream
    Description: LogStream name.
  SubnetId:
    Value: !Ref SubnetId
    Description: Subnet ID
  SubnetId2:
    Value: !Ref SubnetId2
    Description: Subnet ID 2
  PostgresAddress:
    Value: !GetAtt AuroraInstancePostgres.Endpoint.Address
    Description: Postgres Address
  MysqlAddress:
    Value: !GetAtt AuroraInstanceMysql.Endpoint.Address
    Description: Mysql Address