channels:
  - conda-forge
dependencies:
  - python>=3
  - pandoc
  - ipykernel
  - pip
  - pip:
    - nbsphinx
    - nbsphinx-link
    - sphinx==4.3.0
    - sphinx_bootstrap_theme
    - IPython
    - -e ..
